name: customer_section
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/start_img_1.jpg
   - assets/images/start_img_2.jpg
   - assets/images/start_img_3.jpg
  fonts:
    - family: InriaSerif-BoldItalic
      fonts:
        - asset: assets\images\fonts\InriaSerif-BoldItalic.ttf
